var replies = {
    "401":"ERR_NOSUCHNICK",
"402":"ERR_NOSUCHSERVER",
"403":"ERR_NOSUCHCHANNEL",
"404":"ERR_CANNOTSENDTOCHAN",
"405":"ERR_TOOMANYCHANNELS",
"406":"ERR_WASNOSUCHNICK",
"407":"ERR_TOOMANYTARGETS",
"409":"ERR_NOORIGIN",
"411":"ERR_NORECIPIENT",
"412":"ERR_NOTEXTTOSEND",
"413":"ERR_NOTOPLEVEL",
"414":"ERR_WILDTOPLEVEL",
"421":"ERR_UNKNOWNCOMMAND",
"422":"ERR_NOMOTD",
"423":"ERR_NOADMININFO",
"424":"ERR_FILEERROR",
"431":"ERR_NONICKNAMEGIVEN",
"432":"ERR_ERRONEUSNICKNAME",
"433":"ERR_NICKNAMEINUSE",
"436":"ERR_NICKCOLLISION",
"441":"ERR_USERNOTINCHANNEL",
"442":"ERR_NOTONCHANNEL",
"443":"ERR_USERONCHANNEL",
"444":"ERR_NOLOGIN",
"445":"ERR_SUMMONDISABLED",
"446":"ERR_USERSDISABLED",
"451":"ERR_NOTREGISTERED",
"461":"ERR_NEEDMOREPARAMS",
"462":"ERR_ALREADYREGISTRED",
"463":"ERR_NOPERMFORHOST",
"464":"ERR_PASSWDMISMATCH",
"465":"ERR_YOUREBANNEDCREEP",
"467":"ERR_KEYSET",
"471":"ERR_CHANNELISFULL",
"472":"ERR_UNKNOWNMODE",
"473":"ERR_INVITEONLYCHAN",
"474":"ERR_BANNEDFROMCHAN",
"475":"ERR_BADCHANNELKEY",
"481":"ERR_NOPRIVILEGES",
"482":"ERR_CHANOPRIVSNEEDED",
"483":"ERR_CANTKILLSERVER",
"491":"ERR_NOOPERHOST",
"501":"ERR_UMODEUNKNOWNFLAG",
"502":"ERR_USERSDONTMATCH",
"300":"RPL_NONE",
"302":"RPL_USERHOST",
"303":"RPL_ISON",
"301":"RPL_AWAY",
"305":"RPL_UNAWAY",
"306":"RPL_NOWAWAY",
"311":"RPL_WHOISUSER",
"312":"RPL_WHOISSERVER",
"313":"RPL_WHOISOPERATOR",
"317":"RPL_WHOISIDLE",
"318":"RPL_ENDOFWHOIS",
"319":"RPL_WHOISCHANNELS",
"314":"RPL_WHOWASUSER",
"369":"RPL_ENDOFWHOWAS",
"321":"RPL_LISTSTART",
"322":"RPL_LIST",
"323":"RPL_LISTEND",
"324":"RPL_CHANNELMODEIS",
"331":"RPL_NOTOPIC",
"332":"RPL_TOPIC",
"341":"RPL_INVITING",
"342":"RPL_SUMMONING",
"351":"RPL_VERSION",
"352":"RPL_WHOREPLY",
"315":"RPL_ENDOFWHO",
"353":"RPL_NAMREPLY",
"366":"RPL_ENDOFNAMES",
"364":"RPL_LINKS",
"365":"RPL_ENDOFLINKS",
"367":"RPL_BANLIST",
"368":"RPL_ENDOFBANLIST",
"371":"RPL_INFO",
"374":"RPL_ENDOFINFO",
"375":"RPL_MOTDSTART",
"372":"RPL_MOTD",
"376":"RPL_ENDOFMOTD",
"381":"RPL_YOUREOPER",
"382":"RPL_REHASHING",
"391":"RPL_TIME",
"392":"RPL_USERSSTART",
"393":"RPL_USERS",
"394":"RPL_ENDOFUSERS",
"395":"RPL_NOUSERS",
"200":"RPL_TRACELINK",
"201":"RPL_TRACECONNECTING",
"202":"RPL_TRACEHANDSHAKE",
"203":"RPL_TRACEUNKNOWN",
"204":"RPL_TRACEOPERATOR",
"205":"RPL_TRACEUSER",
"206":"RPL_TRACESERVER",
"208":"RPL_TRACENEWTYPE",
"261":"RPL_TRACELOG",
"211":"RPL_STATSLINKINFO",
"212":"RPL_STATSCOMMANDS",
"213":"RPL_STATSCLINE",
"214":"RPL_STATSNLINE",
"215":"RPL_STATSILINE",
"216":"RPL_STATSKLINE",
"218":"RPL_STATSYLINE",
"219":"RPL_ENDOFSTATS",
"241":"RPL_STATSLLINE",
"242":"RPL_STATSUPTIME",
"243":"RPL_STATSOLINE",
"244":"RPL_STATSHLINE",
"221":"RPL_UMODEIS",
"251":"RPL_LUSERCLIENT",
"252":"RPL_LUSEROP",
"253":"RPL_LUSERUNKNOWN",
"254":"RPL_LUSERCHANNELS",
"255":"RPL_LUSERME",
"256":"RPL_ADMINME",
"257":"RPL_ADMINLOC1",
"258":"RPL_ADMINLOC2",
"259":"RPL_ADMINEMAIL",
"005":"RPL_ISUPPORT"
}

    public function __construct()
    {
        $crlf = "\r\n";
        $letter = 'a-zA-Z';
        $number = '0-9';
        $special = preg_quote('[]\`_^{|}~');
        $null = '\\x00';
        $command = "(?P<command>[$letter]+|[$number]{3})";
        $middle = "(?: [^ $null$crlf:][^ $null$crlf]*)";
        // ? provides for relaxed parsing of messages without trailing parameters properly demarcated
        $trailing = "(?: :?[^$null$crlf]*)";
        $params = "(?P<params>$trailing?|(?:$middle{0,14}$trailing))";
        $host = '[^ ]+';
        $nick = "(?:[\\*$letter$special][$letter$number$special-]*)";
        $user = "(?:[^ $null$crlf@]+)";
        $prefix = "(?:(?:(?P<nick>$nick)(?:!(?P<user>$user))?(?:@(?P<host>$host))?)|(?P<servername>$host))";
        $message = "(?P<prefix>:$prefix )?$command$params$crlf";
        $this->message = "/^$message\$/SU";
        $chstring = "[^ \a$null,$crlf]+";
        $channel = $this->channel = "(?:[#&]$chstring)";
        $mask = "(?:[#$]$chstring)";
        $to = "(?:$channel|(?:$user@$host)|$nick|$mask)";
        $target = "(?:$to(?:,$to)*)";
        $this->target = "/^$target$/S";
        this.params = {
            "PASS":      (/^(?:(?P<password>$trailing))$/),
"NICK":      (/^(?:(?P<nickname>$middle|$trailing)(?P<hopcount>$trailing)?)$/),
"USER":      (/^(?:(?P<username>$middle)(?P<hostname>$middle)(?P<servername>$middle)(?P<realname>$trailing))$/),
"SERVER":      (/^(?:(?P<servername>$middle)(?P<hopcount>$middle)(?P<info>$trailing))$/),
"OPER":      (/^(?:(?P<user>$middle)(?P<password>$trailing))$/),
"QUIT":      (/^(?:(?P<message>$trailing)?)$/),
"SQUIT":      (/^(?:(?P<server>$middle)(?P<comment>$trailing))$/),
"JOIN":      (/^(?:(?P<channels>$middle|$trailing)(?P<keys>$trailing)?)$/),
"PART":      (/^(?:(?P<channels>$middle|$trailing)(?P<message>$trailing)?)$/),
"MODE":      (/^(?:(?P<target>$middle|$trailing)(?P<mode>$middle|$trailing)?(?P<params>$trailing)?)$/),
"TOPIC":      (/^(?:(?P<channel>$middle|$trailing)(?P<topic>$trailing)?)$/),
"NAMES":      (/^(?:(?P<channels>$trailing))$/),
"LIST":      (/^(?:(?:(?P<channels>$trailing)|$middle)?(?P<server>$trailing)?)$/),
"INVITE":      (/^(?:(?P<nickname>$middle)(?P<channel>$trailing))$/),
"KICK":      (/^(?:(?P<channel>$middle)(?P<user>$middle|$trailing)(?P<comment>$trailing)?)$/),
"VERSION":      (/^(?:(?P<server>$trailing)?)$/),
"STATS":      (/^(?:(?P<query>$middle|$trailing)(?P<server>$trailing)?)$/),
"LINKS":      (/^(?:(?P<remoteserver>$middle)?(?P<servermask>$trailing)?)$/),
"TIME":      (/^(?:(?P<server>$trailing)?)$/),
"CONNECT":      (/^(?:(?P<targetserver>$middle|$trailing)(?P<port>$middle|$trailing)?(?P<remoteserver>$trailing)?)$/),
"TRACE":      (/^(?:(?P<server>$trailing)?)$/),
"ADMIN":      (/^(?:(?P<server>$trailing)?)$/),
"INFO":      (/^(?:(?P<server>$trailing)?)$/),
"PRIVMSG":      (/^(?:(?P<receivers>$middle)(?P<text>$trailing))$/S),
"NOTICE":      (/^(?:(?P<nickname>$middle)(?P<text>$trailing))$/S),
"WHO":      (/^(?:(?P<name>$middle|$trailing)(?P<o>$trailing)?)$/),
"WHOIS":      (/^(?:(?P<server>$middle)?(?P<nickmasks>$trailing))$/),
"WHOWAS":      (/^(?:(?P<nickname>$middle|$trailing)(?P<count>$middle|$trailing)?(?P<server>$trailing)?)$/),
"KILL":      (/^(?:(?P<nickname>$middle)(?P<comment>$trailing))$/),
"PING":      (/^(?:(?P<server1>$middle|$trailing)(?P<server2>$trailing)?)$/),
"PONG":      (/^(?:(?P<daemon>$middle|$trailing)(?P<daemon2>$trailing)?)$/),
"ERROR":      (/^(?:(?P<message>$trailing))$/),
"AWAY":      (/^(?:(?P<message>$trailing)?)$/),
"REHASH":      (/^$/),
"RESTART":      (/^$/),
"SUMMON":      (/^(?:(?P<user>$middle|$trailing)(?P<server>$trailing)?)$/),
"USERS":      (/^(?:(?P<server>$trailing)?)$/),
"WALLOPS":      (/^(?:(?P<text>$trailing))$/),
"USERHOST":      (/^(?:(?P<nickname1>$middle|$trailing)(?P<nickname2>$middle|$trailing)?(?P<nickname3>$middle|$trailing)?(?P<nickname4>$middle|$trailing)?(?P<nickname5>$trailing)?)$/),
"ISON":      (/^(?:(?P<nicknames>(?:$middle )*$trailing))$/),
"PROTOCTL":      (/^(?:()(?P<proto>$trailing))$/)
        };
        $xdelim = "\001";
        $middle = "(?:[^:]+)";
        $trailing = "(?:[^"+xdelim+"]+)";
        this.ctcp = "/^"+xdelim+"(?P<command>[^ ]+)(?P<params> [^"+xdelim+"]+)?"+xdelim+"$/S";
        this.ctcpParams = {
            "FINGER":      "/^(?::(?P<user>"+trailing+"))?$/",
"VERSION":      "/^(?:(?P<name>"+middle+"):(?P<version>"+middle+"):(?P<environment>"+trailing+"))?$/",
"SOURCE":      "/^(?:(?P<host>"+middle+"):(?P<directories>"+middle+"):(?P<files>"+trailing+"))?$/",
"USERINFO":      "/^(?::(?P<user>"+trailing+"))?$/",
"CLIENTINFO":      "/^(?::(?P<client>"+trailing+"))?$/",
"ERRMSG":      "/^(?:(?P<query>.+)(?: :(?P<message>"+trailing+"))?)$/U",
"PING":      "/^(?:(?P<timestamp>"+trailing+"))$/",
"TIME":      "/^(?::(?P<time>"+trailing+"))$/",
"ACTION":      "/^(?::(?P<action>"+trailing+"))$/",
        };
    }
